name: Login using OICD with an Azure Managed Identity (user assigned)

on: 
  workflow_dispatch:
    inputs:
      AZURE_SUBSCRIPTION_ID:
        type: string
        description: 'Azure subscription id'
        required: true

jobs:
  validate_and_deploy:
    runs-on: ubuntu-latest 
    steps:
    
    # Prase AZURE_MSI secret
    - name: Prase AZURE_MSI secret
      id: msiPrincipal
      env:
        SECRET: ${{ secrets.AZURE_MSI }}
      run: |
        clientId=$(echo $SECRET | jq -r '.["clientId"]')
        tenantId=$(echo $SECRET | jq -r '.["tenantId"]')
        subscriptionId=$(echo $SECRET | jq -r '.["id"] | split("/")[2]')
        echo "::add-mask::$clientId"
        echo "::add-mask::$tenantId"
        echo "::add-mask::$subscriptionId"
        echo clientId=$clientId >> $GITHUB_ENV
        echo tenantId=$tenantId >> $GITHUB_ENV
        echo subscriptionId=$subscriptionId >> $GITHUB_ENV

        principalId=$(echo $SECRET | jq -r '.["principalId"]')
        echo setting objectId to $principalId
        echo "objectId=$principalId" >> $GITHUB_OUTPUT    

    # Login
    - name: 'Azure login'
      uses: azure/login@v1
      with:
        client-id: ${{ steps.msiPrincipal.outputs.clientId }}
        tenant-id: ${{ steps.msiPrincipal.outputs.tenantId }}
        subscription-id: ${{ steps.msiPrincipal.outputs.subscriptionId }}
        
